---
# tasks file for config

- name: CONFIG APT
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "etc/apt/apt.conf.d/10periodic"

- name: CONFIG dpkg
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "etc/apt/apt.conf.d/20dpkg"

- name: CONFIG purge default config
  file:
    path: "/etc/apt/apt.conf.d/{{ item }}"
    state: absent
  with_items:
    - "{{ apt_conf_purge_list }}"
  when: apt_conf_purge_manage
