---
# tasks file for apt

- include: preferences.yml
  tags:
    - system
    - apt
    - preferences
    - apt-manage

- include: repositories.yml
  tags:
    - system
    - apt
    - repository
    - apt-manage

- include: packages.yml
  tags:
    - system
    - apt
    - packages
