---
# tasks file for apt

# Sources list
## Stretch
- name: CONFIG stretch official sources.list
  apt_repository:
    repo: "{{ item }} http://httpredir.debian.org/debian/ stretch main contrib non-free"
    filename: stretch
    update_cache: no
  with_items:
    - deb
    - deb-src
  when: apt_src_list_manage and apt_stretch_manage

- name: CONFIG stretch backports sources.list
  apt_repository:
    repo: "deb http://httpredir.debian.org/debian/ stretch-{{ item }} main contrib non-free"
    filename: stretch.bpo
    update_cache: no
  with_items:
    - backports
  when: apt_src_list_manage and apt_stretch_manage
