---
# tasks file for packages

# Packages
- name: INSTALL useful tools packages
  apt:
    name: '{{ item }}'
    state: '{{ apt_tools_state }}'
  with_items:
    - '{{ apt_tools_list }}'
  when: apt_tools_manage

- name: INSTALL unattended-upgrades
  apt:
    pkg: "unattended-upgrades"
    state: "{{ 'latest' if apt_unattended_upgrades else 'absent' }}"
    update_cache: yes
  when: apt_unattended_upgrades

- name: INSTALL purge useless packages
  apt:
    name: '{{ item }}'
    state: '{{ apt_unwanted_pkg_state }}'
  with_items:
    - '{{ apt_unwanted_pkg_list }}'
  when: apt_unwanted_pkg_manage
