---
# tasks file for repositories

# Sources list
## Stretch {{{
- name: REPOS stretch official sources.list
  apt_repository:
    repo: "{{ item }} http://httpredir.debian.org/debian/ stretch main contrib non-free"
    filename: stretch
    update_cache: no
  with_items:
    - deb
    - deb-src
  notify: aptitude update
  when: apt_src_list_manage and apt_stretch_manage

- name: REPOS stretch security sources.list
  apt_repository:
    repo: "{{ item }} http://httpredir.debian.org/debian-security/ stretch/updates main contrib non-free"
    filename: stretch.security
    update_cache: no
  with_items:
    - deb
    - deb-src
  notify: aptitude update
  when: apt_src_list_manage and apt_stretch_manage

- name: REPOS stretch backports sources.list
  apt_repository:
    repo: "deb http://httpredir.debian.org/debian/ stretch-{{ item }} main contrib non-free"
    filename: stretch.bpo
    update_cache: no
  with_items:
    - backports
  notify: aptitude update
  when: apt_src_list_manage and apt_stretch_manage
# }}}

## Purge sources.list file
- name: REPOS remove sources.list file
  file:
    path: /etc/apt/sources.list
    state: absent
  notify: aptitude update
  when: apt_purge_src_list_file
